"""Integration test: replays the small synthetic capture file in
tests/fixtures/sample_capture.csv (generated by the WiSense CSV
capture format, see FileCSISource) through the full pipeline --
FileCSISource -> CSIBuffer -> calibration -> PresenceDetector -- to
verify the pieces work together end to end, not just in isolation.

The fixture file simulates: ~3s empty room, ~4s of a person moving
around, ~3s empty room again, at a nominal 20 Hz capture rate. It is
synthetic test data (see its generation comment below), never
presented as a real capture.
"""

from pathlib import Path

from wisense.core.calibration import calibrate
from wisense.core.connection import FileCSISource
from wisense.core.stream import CSIBuffer
from wisense.presence.detector import PresenceDetector

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "sample_capture.csv"


def test_fixture_file_exists():
    assert FIXTURE_PATH.exists(), "sample_capture.csv fixture is missing"


def test_end_to_end_presence_pipeline():
    # Calibrate on the first ~2s (empty-room) portion of the capture.
    # We use realtime=True here so calibrate()'s wall-clock duration
    # window lines up with the *recorded* timestamps in the file
    # (calibrate() is designed around live, real-time sources; without
    # realtime pacing a file source would replay instantly and consume
    # far more of the file than the calibration window is meant to
    # represent).
    with FileCSISource(FIXTURE_PATH, realtime=True) as calib_source:
        profile = calibrate(calib_source, duration_seconds=2.0)

    assert profile.n_frames > 0
    assert profile.n_subcarriers == 16

    # Now replay the whole file through a buffer and check presence
    # flips on during the "motion" segment in the middle of the file.
    with FileCSISource(FIXTURE_PATH) as source:
        buffer = CSIBuffer(capacity=256)
        buffer.fill_from_source(source)

    assert len(buffer) == 200

    all_frames = buffer.snapshot()
    detector = PresenceDetector()

    empty_window = all_frames[10:40]
    motion_window = all_frames[80:120]
    empty_again_window = all_frames[170:200]

    empty_result = detector.detect(empty_window, calibration=profile)
    motion_result = detector.detect(motion_window, calibration=profile)
    empty_again_result = detector.detect(empty_again_window, calibration=profile)

    assert empty_result.present is False
    assert motion_result.present is True
    assert empty_again_result.present is False
